services:
  - type: web
    name: tyla-instagram
    env: node
    region: oregon
    plan: starter
    buildCommand: chmod +x install-chrome-render.sh && ./install-chrome-render.sh && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
